### PR TITLE
fix link in edit branch versioning java sample

### PR DESCRIPTION
**Pull request by markjdugger**
### Description

Checklist:
- [x] Set target branch to master (current release) or dev (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

### CODE REVIEW

**Comment by markjdugger** [comment]
@jenmerritt The Damage to Damage to commercial buildings link is broken, as demonstrated on the live web site, pictured below:
image

This fix is to remove the double quotes from the URL. (Markdown link must NOT have double quotes):
https://github.com/Esri/arcgis-runtime-samples-java/pull/572/files#diff-c3871ab7fcc614fac38b75ced6bebb5428e49fcb4abc9db245d6dc660c3f8ff7R43

**Comment by markjdugger** [comment]
By removing the double quotes, the link works, as demonstrated in this preview:

https://mark9880-edit-branch-versioning-preview-dev.developers.arcgis.com/java/latest/java/sample-code/edit-with-branch-versioning/#about-the-data

**Comment by markjdugger** [comment]
@jenmerritt Just occurred to me that this change also needs to be applied to the `dev` branch. 
So you should either (1) create another PR that merges to `dev`. or (2) cherry-pick the single commit from this PR into `dev`.
I'll leave that task to you.

**Review by jenmerritt — APPROVED** [review]
Good spot, thanks @markjdugger ! I'll handle updating `dev`.

**Review by JonLavi — APPROVED** [review]
👍

**Pull request merged**
