### PR TITLE
Sample Update: Add Dynamic Entity Layer Sample

### PR DESCRIPTION
**Pull request by 01smito01**
### Description

A couple of fixes to _Add Dynamic Entity Layer_:
- Changed data purge duration from 5 seconds to 5 minutes, in line with sample design.
- Updated slider to have a maximum of 16 previous observations, with the default remaining at 5. This is in line with Qt and .NET.
- Updated the "track lines" and "previous observations" checkboxes to be enabled by default. This is also in line with Qt and .NET (or at least the implementation details in common samples).

Checklist:
- [x] Set target branch to main (current release) or v.next (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

### CODE REVIEW

**Comment by 01smito01** [comment]
@Luiy0 can you give this a first review?

**Review by Luiy0 — APPROVED** [review]
Looks good @01smito01, thanks for the updates.

**Comment by 01smito01** [comment]
Thank you, assigning to @D-R-Smith for second review.

**Review by D-R-Smith — APPROVED** [review]
@01smito01 looks good to me

**Comment by 01smito01** [comment]
Thanks @D-R-Smith, merging.

**Pull request merged**
