### PR TITLE
Replace scene service

### PR DESCRIPTION
**Pull request by jenmerritt**
### Description

Replaces a broken scene service to improve these samples.

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

### CODE REVIEW

**Comment by jenmerritt** [comment]
@Rachael-E please could you review? Relates to 7495, see comments in there. I think we should replace this scene service to improve these samples in the next release.

**Comment by jenmerritt** [comment]
@Lui12799 could you do a first review here?

**Review by Luiy0 — APPROVED** [review]
Looks good @jenmerritt

**Review by Rachael-E — APPROVED** [review]
looks good @jenmerritt . Makes sense having the standard World Elevation 3D service for these samples! It would be worth letting Kathleen know about the data changed here: some of these may be on the list of samples her team run image comparison tests on, and I suspect the surface change would flag up a difference.

**Comment by jenmerritt** [comment]
Thanks @Rachael-E , she reported the issue so will definitely be verifying 👍

**Pull request merged**
