### PR TITLE
Updating doc link to Java API's

### PR DESCRIPTION
**Pull request by mfeigl**
### Description

Updating link to be Java specific. 

Checklist:
- [x] Set target branch to main (current release) or v.next (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

### CODE REVIEW

**Comment by mfeigl** [comment]
@D-R-Smith could you please do the first review?

**Review by D-R-Smith — APPROVED** [review]
@mfeigl looks okay

**Comment by mfeigl** [comment]
@colinanderson could you please do a second review?

**Review by colinanderson — APPROVED** [review]
@mfeigl looks ok

**Pull request merged**
