### PR TITLE
Refactor format coordinates

### PR DESCRIPTION
**Pull request by jenmerritt**
### Description
Follows feedback from release testing, refer to issue 7521.

- set a custom view on the vbox to have more control over the contents
- reduced the amount of text to make it clearer and also set a width on the vbox
- reported bugs in the callout for future development
- updated screenshot to match
- also removed animation from callout as it's buggy (disappears if you click multiple times)

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

### CODE REVIEW

**Comment by jenmerritt** [comment]
First review please @Luiy0

**Review by Luiy0 — APPROVED** [review]
Nice updates @jenmerritt!

**Comment by jenmerritt** [comment]
@Rachael-E please could I get a second review?

**Review by Rachael-E — APPROVED** [review]
thanks @jenmerritt , nice use of the custom view here for the callout, fixes up that bug nicely.

**Pull request merged**
