### PR TITLE
Review use of commons.io

### PR DESCRIPTION
**Pull request by mbcoder**
### Description

PR to review the use of commons.io.  Have either removed redundant references of updated and tested with 2.11.0

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

### CODE REVIEW

**Comment by mbcoder** [comment]
PR for main branch https://github.com/Esri/arcgis-maps-sdk-java-samples/pull/782

**Review by jenmerritt — APPROVED** [review]
LGTM. No compilation errors and spot ran a few.

**Comment by mbcoder** [comment]
@colinanderson second review?

**Review by colinanderson — APPROVED** [review]
@mbcoder looks ok.

**Pull request merged**
