### PR TITLE
Added check that authentication went through

### PR DESCRIPTION
**Pull request by john0005**
@tyle8552 Can you check this? Added a line to make sure that the authentication went through before moving on. If cancel was hit an error would be thrown because configuration was null.

### CODE REVIEW

**Comment by ghost** [comment]
@john0005 Looks fine. Thanks

**Review by ghost — APPROVED** [review]

**Comment by zz0807** [comment]
hello I am a new leaner to study arcgis sdk for java.I have a problem about how to open shape file with the latest version of sdk.Can you please tell me what to do?I am really puzzled for a long time.来自我的华为手机-------- 原始邮件 --------主题：Re: [Esri/arcgis-runtime-samples-java] Added check that authentication went through (#116)发件人：Tyler Schiewe 收件人：Esri/arcgis-runtime-samples-java 抄送：Subscribed @tyle8552 approved this pull request.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Esri/arcgis-runtime-samples-java","title":"Esri/arcgis-runtime-samples-java","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Esri/arcgis-runtime-samples-java"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tyle8552 approved #116"}],"action":{"name":"View Pull Request","url":"https://github.com/Esri/arcgis-runtime-samples-java/pull/116#pullrequestreview-20796338"}}}

**Comment by john0005** [comment]
@zz0807 Opening a Shape file is not possible yet with the latest version of Quartz. Update 1 which we are working on now, should be released here in 2 months, may have it to were you can open a Shape File using a Local Server. For opening one without using a Local Server seems that it will come in the next update.

**Comment by zz0807** [comment]
thank you very much来自我的华为手机-------- 原始邮件 --------主题：Re: [Esri/arcgis-runtime-samples-java] Added check that authentication went through (#116)发件人：JC Malott 收件人：Esri/arcgis-runtime-samples-java 抄送：zz ,Mention @zz0807 Opening a Shape file is not possible yet with the latest version of Quartz. Update 1 which we are working on now, should be released here in 2 months, may have it to were you can open a Shape File using a Local Server. For opening one without using a Local Server seems that it will come in the next update.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Esri/arcgis-runtime-samples-java","title":"Esri/arcgis-runtime-samples-java","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Esri/arcgis-runtime-samples-java"}},"updates":{"snippets":[{"icon":"PERSON","message":"@john0005 in #116: @zz0807 Opening a Shape file is not possible yet with the latest version of Quartz. Update 1 which we are working on now, should be released here in 2 months, may have it to were you can open a Shape File using a Local Server. For opening one without using a Local Server seems that it will come in the next update. "}],"action":{"name":"View Pull Request","url":"https://github.com/Esri/arcgis-runtime-samples-java/pull/116#issuecomment-278998580"}}}

**Pull request merged**
