### PR TITLE
picture marker location update

### PR DESCRIPTION
**Pull request by mbcoder**
### Description

This is a fix for the Picture Marker Symbol in the 100.15 branch.  The resource has gone away.  This was fixed in 200.x so I'm just porting the fix back to 100.15

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

### CODE REVIEW

**Review by D-R-Smith — APPROVED** [review]
@mbcoder This change looks good to me (it worked locally). I don't know how the branches work in the samples so I'll assume this is the correct branch.

**Comment by 01smito01** [comment]
The same resource was also used in `RenderMultilayerSymbolsSample` so I've changed the URL there as well.

**Comment by mbcoder** [comment]
Good catch @01smito01 

@Rachael-E second review?

**Comment by mbcoder** [comment]
I've added the WMS fix too which is just a port from 200 code too

**Review by Rachael-E — APPROVED** [review]

**Pull request merged**
