### PR TITLE
Updating portal item to use the data in ArcGISRuntimeSDK.

### PR DESCRIPTION
**Pull request by mfeigl**
### Description

The data in the original sample comes from the elsewhere and we need to use the data in ArcGISRuntimeSDK.

Checklist:
- [x] Set target branch to main (current release) or v.next (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

### CODE REVIEW

**Comment by mfeigl** [comment]
@colinanderson could you please review?

**Review by colinanderson — APPROVED** [review]
@mfeigl looks ok

**Comment by mfeigl** [comment]
@alan-edi could you please do a second review?

**Review by alan-edi — APPROVED** [review]
@mfeigl LGTM

**Pull request merged**
