### PR TITLE
Prep Symbols (scene) for Beta

### PR DESCRIPTION
**Pull request by jenmerritt**
### Description

- modularize
- update to better viewpoint
- replace colors

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

### CODE REVIEW

**Comment by jenmerritt** [comment]
@mbcoder please could I get a review?

**Review by mbcoder — APPROVED** [review]
This looks good to me

**Comment by jenmerritt** [comment]
@Luiy0 second review please

**Review by Luiy0 — APPROVED** [review]
LGTM

**Pull request merged**
