### PR TITLE
Fix colormap to use Color

### PR DESCRIPTION
**Pull request by D-R-Smith**
### Description
The `ColormapRenderer` has changed to use JavaFX `Color` instead of ARGB integers.

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

### CODE REVIEW

**Comment by D-R-Smith** [comment]
Assigning to @jenmerritt for a first review please.

**Review by jenmerritt — APPROVED** [review]
LGTM @D-R-Smith

**Comment by D-R-Smith** [comment]
Assigning to @Luiy0 for a second review please.

**Review by Luiy0 — APPROVED** [review]
All good!

**Pull request merged**
