### PR TITLE
Release 200.1.0

### PR DESCRIPTION
**Pull request by jenmerritt**
### Description
Updates arcgisversion to 200.1.0

Checklist:
- [ ] Set target branch to main (current release) or v.next (next release)
- [ ] Request a reviewer
- [ ] Assign a reviewer
- [ ] Tag reviewer in comment

### CODE REVIEW

**Comment by jenmerritt** [comment]
@D-R-Smith please could you review? Updates 211 samples to 200.1.0 in preparation for release.

**Review by D-R-Smith — APPROVED** [review]
@jenmerritt this change looks good to me

**Comment by jenmerritt** [comment]
@Luiy0 please could you also check this branch before I merge? Thanks

**Review by Luiy0 — APPROVED** [review]
LGTM @jenmerritt

**Pull request merged**
