### PR TITLE
fix/spatial-operations-reset-button

### PR DESCRIPTION
**Pull request by JonLavi**
Hi both,
I've done a quick improvement on the 'SpatialOperations' sample.
When redoing the readme, I found that the reset button doesn't reset the selected operation (just the geometry).
Addition: added a 'NONE' operation, made it selected when the sample starts, and pressing reset selects this option again.
If you have a moment to review, I'd be thankful to hear what you think.

### CODE REVIEW

**Review by Rachael-E — APPROVED** [review]
@JonLavi nice! All looks good.

**Comment by tschie** [comment]
@JonLavi  how about
```java
geomOperationBox.setOnAction(e -> {
        Geometry resultPolygon;
        OPERATION_TYPE operation = geomOperationBox.getSelectionModel().getSelectedItem();
        switch (operation) {
          case UNION:
            resultPolygon = GeometryEngine.union(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case DIFFERENCE:
            resultPolygon = GeometryEngine.difference(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case SYMMETRIC_DIFFERENCE:
            resultPolygon = GeometryEngine.symmetricDifference(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case INTERSECTION:
            resultPolygon = GeometryEngine.intersection(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case NONE:
            resultGeomOverlay.getGraphics().clear();
          default:
            return;
        }

        // update result as a red (0xFFE91F1F) geometry
        SimpleFillSymbol redSymbol = new SimpleFillSymbol(SimpleFillSymbol.Style.SOLID, 0xFFE91F1F, line);
        resultGeomOverlay.getGraphics().add(new Graphic(resultPolygon, redSymbol));
      });
```

Then you could get rid of the reset button

**Review by tschie — COMMENTED** [review]
@JonLavi  how about
```java
geomOperationBox.setOnAction(e -> {
        Geometry resultPolygon;
        switch (geomOperationBox.getSelectionModel().getSelectedItem()) {
          case UNION:
            resultPolygon = GeometryEngine.union(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case DIFFERENCE:
            resultPolygon = GeometryEngine.difference(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case SYMMETRIC_DIFFERENCE:
            resultPolygon = GeometryEngine.symmetricDifference(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case INTERSECTION:
            resultPolygon = GeometryEngine.intersection(polygon1.getGeometry(), polygon2.getGeometry());
            break;
          case NONE:
            resultGeomOverlay.getGraphics().clear();
          default:
            return;
        }

        // update result as a red (0xFFE91F1F) geometry
        SimpleFillSymbol redSymbol = new SimpleFillSymbol(SimpleFillSymbol.Style.SOLID, 0xFFE91F1F, line);
        resultGeomOverlay.getGraphics().add(new Graphic(resultPolygon, redSymbol));
      });
```

Then you could get rid of the reset button

**Comment by JonLavi** [comment]
@tschie sounds good to me!
Had to modify it a little to make sure the geometries are reset every time a choice is made.
Reset button is now gone.
Would you have a quick look to see if it still behaves as expected?

**Comment by tschie** [comment]
@JonLavi Looks good. Only other things I can think of are 
1. The image needs to be updated (no more reset button)
2. The label maybe isn't necessary. You could probably just show the combobox (without the background vbox)
3. The combobox could be a little wider so symmetric_difference doesn't get cut off

Good to merge when (1) is done. Up to you if you want to make the other changes.

**Comment by JonLavi** [comment]
Thanks @tschie, all those changes implemented.

**Pull request merged**
