### PR TITLE
added tick marks and label for rotation angle

### PR DESCRIPTION
**Pull request by doneill**
@john0005 @tyle8552 I added tick marks and a label to show the rotation angle. Please review.

### CODE REVIEW

**Comment by john0005** [comment]
I feel like the label is not need since it just repeats what the tick marks are displaying. If the label is kept I also feel like it should display 0 when the application first starts because it doesn't display for me until the rotation is changed.

Other than that I really like the addition of the tick marks.

**Comment by ghost** [comment]
@doneill I agree, the label is unnecessary. If you're worried about the labels/ticks not being easily visible, I suggest adding a semi-transparent black background like many of our other samples. See the Update Attributes (Editing) sample's CSS as an example. Other than that, looks good. Thanks.

**Comment by doneill** [comment]
@tyle8552 @john0005 I removed the label.  Only added because all other SDK samples label, the tick marks are a nice effect on the JavaFX slider control, agree that it is redundant with the label.

**Comment by ghost** [comment]
@doneill good to merge.

**Comment by john0005** [comment]
Going to merge this so I can update the dev site today.

**Pull request merged**
