### PR TITLE
Remove initowner from dialog

### PR DESCRIPTION
**Pull request by Rachael-E**
### Description

As discussed with @mbcoder, removing initOwner from this dialog as it is causing conflicts with the sample viewer. @JonLavi @jenmerritt can you review please? I have tested this both locally via the IDE and via the sample viewer on Mac and it works as expected. Please could you sanity check the dialog still appears as expected for you on Windows? Thanks. 

Checklist:
- [x] Set target branch to master (current release) or dev (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

### CODE REVIEW

**Review by jenmerritt — APPROVED** [review]
Tested Feature Layer Query Sample on Windows.

- IDE - dialog displays when entering blank state or incorrect state (works as it did before)
- SV - dialog now displays when entering blank state or incorrect state. NullPointerException no longer occurrs.

So looks good to me!

**Comment by JonLavi** [comment]
For some weird reason I can't leave a proper review (so just merge if you need to)!

I've tested with adding 
```
dialog.initOwner(Stage.getWindows().stream().filter(Window::isShowing).findFirst().orElse(null));
```

and it seems to work fine in both the SV and the isolated sample.

This probably works because `Stage` can be found when running from the SV as it then grabs the SV's stage.

I don't know if this is necessary at all still, so just putting it out there.

**Comment by colinanderson** [comment]
I doubt this is the right fix. I suspect you were setting the owner to null because the way the sample viewer creates the node means it doesn't have a window when you were calling `stackPane.getScene().getWindow()`. Not having an owner might have changed the modality of your dialog. See https://stackoverflow.com/questions/37181445/initowner-role-javafx.

**Comment by colinanderson** [comment]
At least two differences when there is no owner
- the dialog does not get the app's icon.
- the dialog appears as a separate app on the task bar e.g.
image

**Pull request merged**
