### PR TITLE
Dop/add build script

### PR DESCRIPTION
**Pull request by doneill**
gradle build script to run samples and instructions for running the samples and importing into IntelliJ IDEA & Eclipse.

### CODE REVIEW

**Comment by doneill** [comment]
@mbcoder @eric906 I have included developer instructions for your review.  Please review!

**Comment by eric906** [comment]
@doneill What is it that we need to review?

**Comment by doneill** [comment]
@eric906 The [Run the Samples](https://github.com/Esri/arcgis-runtime-samples-java/tree/dop/add-build-script#run-the-samples) section of the README which shows how to run the samples from a terminal, IntelliJ IDEA, and Eclipse.  Also note the source folder structure has changed to **src/main/java** and how to edit the build.gradle script to run each sample.

**Comment by eric906** [comment]
@doneill in the section "Configure remote upstream for your fork ", don't we want folks to navigate into the directory they've just cloned? Before they do "git remote -v" ?

**Comment by doneill** [comment]
@eric906 Yes, good catch, made a small update to address.

**Comment by eric906** [comment]
@doneill : Thanks. Another one: under "Run the samples", what "samples project" is it talking about here?

<I>Once the samples have been forked/cloned locally to your machine you need to add the following from the SDK download.

Copy the contents of JavaSDK100.0.0/ArcGISRuntime100.0.0/ to the root of your <b>samples project</b>.</I>

**Comment by eric906** [comment]
@doneill a few typos:
- In "Eclipse" section, in the second "fourth" step: <I><b>Now</b> should now see the Gradle tasks view, if you...</I> 
- In "Gradle" section: an "AND" instead of an "AN" - <I> build and run any samples from a terminal prompt or from within <b>and</b> IDE that supports gradle..</I>.  Also notice there are 2 periods at the end of the sentence.

**Comment by doneill** [comment]
@eric906 Good catches, I have fixed the typos.

**Comment by eric906** [comment]
@doneill I followed the instructions in the Eclipse section. When I Run the task....nothing happens.

**Comment by doneill** [comment]
@eric906 Can you run a sample from a terminal prompt?  After you setup in Eclipse you are calling Run from the Gradle Tasks window as shown below:

eclipse-gradletasks

**Comment by doneill** [comment]
@eric906 And your project structure in Eclipse looks like the following:  

eclipse-project-structure

**Comment by eric906** [comment]
Hmmm. Something was WAY off from my side.

**Comment by eric906** [comment]
@doneill @willcrick    So, I'm stuck back at "Run the samples". See my note above. It talks about "your sample project"...but looking through the workflow, there isn't a sample project created. Yet. Or did I miss something?

**Comment by doneill** [comment]
@eric906 The samples project is the root of the forked/cloned repository.  After you fork the repo then clone it locally you cd into the **arcgis-runtime-samples-java** directory.  You are now in the samples project directory.  This is the root level directory you run gradle commands from and use to import into IDE's.  Does that make sense?  If so, how can I articulate that better to make it clearer?

**Comment by doneill** [comment]
@eric906 I created a little more context about the samples project directory, let me know the latest update helps.

**Comment by eric906** [comment]
@doneill  Yeah, thats what I thought. Its just that the term "Project" isn't used until this point, and that sort of made me pause. You really want people to know that they next need to copy JavaSDK100.0.0/ArcGISRuntime100.0.0/ to the root of their cloned repo. Or something like that. ?

**Comment by doneill** [comment]
@eric906 I removed the term project and replace with samples repo, also added screenshots of the **project** directory structure once imported into an IDE.  Thanks for the suggestion, let me know if it addresses your concerns.

**Comment by eric906** [comment]
@doneill  After I've copied ArcGISRuntime and ArcGIS jar into the directory, my folder structure is missing some things that you have in the screenshot: It's missing the "gradle" folder. Where do I get that from?
image

**Comment by doneill** [comment]
@eric906 It is in the repo, looks like you are the [master](https://github.com/Esri/arcgis-runtime-samples-java/tree/master) branch, you need to checkout my branch with the following:  

```
git fetch origin
git checkout -b dop/add-build-script origin/dop/add-build-script
```

**Comment by eric906** [comment]
@doneill Oh crap. That's right.

**Comment by eric906** [comment]
@doneill Ok, getting closer. Now, when I run gradlew.bat, I get Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain. I need some gradle jars?

**Comment by eric906** [comment]
@doneill Ok. I did something...and now my environment is locating my gradle jars. So I am good to go. Still...I'm not 100% certain these instructions are clear to me from beginning to end. But I got it to work by doing something.

**Comment by doneill** [comment]
@eric906 DId you run a task on your first `gradlew.bat` command call?

**Comment by doneill** [comment]
@mbcoder @eric906 put it through the test today, can you review as well as I have provided some updates per his excellent feedback?

**Comment by doneill** [comment]
@mbcoder Did you get a chance to review this today?  

@eric906 Any more comments from your review?

**Comment by doneill** [comment]
@yferrera Please review this PR based on some feedback from @eric906 as I am keen to get this merged so that we have instructions to build/run the samples.

**Comment by doneill** [comment]
@eric906 @mbcoder @yferrera I added a **Change Basemaps** sample based on my branch, so I could test it.  Give it a review with the run samples workflows.

**Comment by eric906** [comment]
@doneill : Finally getting to this now. Sorry for the delay

**Comment by eric906** [comment]
@doneill I have reviewed this sample. Works fine for me. I noticed a slight lag in loading each basemap. Is this expected? It seems to be performing slow.

**Comment by eric906** [comment]
@doneill Regarding the <I>gradlew clean run --info</I> command, if I follow your instructions chronologically, I get "Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain".

If instead, I import the repo as a gradle project FIRST, then go back to the command line and execute gradlew clean run --info....then everything works fine.

Ideas?

**Comment by doneill** [comment]
@eric906 are you running `./gradlew clean run --info`?

**Comment by doneill** [comment]
@eric906 I notice in all the samples the basemaps are slow to load.  Try running **Add Graphics with Symbols**.

**Comment by doneill** [comment]
@eric906 Am I good to merge?

**Comment by eric906** [comment]
@doneill Yessir. Merge away

**Comment by eric906** [comment]
@doneill running ./gradlew clean run --info. Yes. On Windows. so no ./ . it only works AFTER I import into Eclipse.

**Comment by doneill** [comment]
On windows `>  gradlew.bat clean run --info`.  What about using run from the Eclipse gradle tasks window?

**Comment by eric906** [comment]
@doneill From Eclipse....no. Same problem. 
But strange...after failing first at the command line, then importing to eclipse and failing there too, i'll go back to command line....and it all works from then on.

**Pull request merged**
