### PR TITLE
Fixing run bug fo ApplyMosaicRuleToRasters

### PR DESCRIPTION
**Pull request by mfeigl**
### Description

The sample was unable to run and failed upong execution, simple fix. 

Checklist:
- [x] Set target branch to main (current release) or v.next (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

### CODE REVIEW

**Comment by mfeigl** [comment]
@D-R-Smith , could you please review?

**Review by D-R-Smith — APPROVED** [review]
@mfeigl looks fine to me

**Comment by mfeigl** [comment]
@mbcoder could you please do a second review?

**Review by mbcoder — APPROVED** [review]
Looks safe to me

**Pull request merged**
