### PR TITLE
V.next into main to sync up

### PR DESCRIPTION
**Pull request by mfeigl**
### Description
After `main` was merged into `v.next`, git has gotten itself confused over commits and thinks there is a difference between the two branches. I cannot tell any difference by looking at the files in both `main` and `v.next` - so, as suggested, it may be a good idea to merge `v.next` into `main` and sync git's understanding of the two branches. 

Checklist:
- [x] Set target branch to main (current release) or v.next (next release)
- [x] Request a reviewer
- [x] Assign a reviewer
- [x] Tag reviewer in comment

### CODE REVIEW

**Comment by mfeigl** [comment]
@D-R-Smith could you please reviw this?

**Review by D-R-Smith — APPROVED** [review]
@mfeigl looks okay

**Comment by mfeigl** [comment]
@jenmerritt could you please do the second review?

**Review by jenmerritt — APPROVED** [review]
Happy to approve based on our discussion and proposed changed workflows.

**Pull request merged**
