### PR TITLE
100.9.0

### PR DESCRIPTION
**Pull request by Rachael-E**
New samples and updates for 100.9.0 release.

Not to be merged until 100.9.0 is live AND @markjdugger has confirmed the webpages build from this branch as expected.

@JonLavi @jenmerritt @mbcoder

### CODE REVIEW

**Review by JonLavi — APPROVED** [review]
All good @Rachael-E . Had a skim over this. Any of these changes will have been reviewed and approved in the appropriate branch, so should be good to merge 👍

**Comment by markjdugger** [comment]
@Rachael-E @JonLavi ~I am unable to built a `-preview` branch in AFD that uses this PR for publishing to the website.~

@Rachael-E @mbcoder @JonLavi
**I got Thad to create the `-preview` branch on my behalf. So, you can do a sanity check at this URL:**
https://java-u9-samples-preview-dev.developers.arcgis.com/java/latest/java/sample-code/ 
 (Seems I no longer have adequate permissions to publish a preview branch in AFD repo.)

Of course, the 100.9.0 samples will not actually appear on the public web site until next Thursday (Sep 3, 2020). But with the above preview branch anyone can verify that the generated HTML has all the content expected and that all pages display properly.

**Review by mbcoder — APPROVED** [review]
A nice small pull request.  Yes looks good to me.

**Review by jenmerritt — APPROVED** [review]
Looks good to me!

**Comment by markjdugger** [comment]
@Rachael-E I created a very small PR #549, which corrects title capitalization for 3 samples. I discovered these discrepancies while reviewing the preview branch mentioned in comment above:
https://github.com/Esri/arcgis-runtime-samples-java/pull/548#issuecomment-680531380

**Pull request merged**
